name: Deploy site
on:
  push:
    branches:
    - main
  workflow_dispatch: # Manual builds
    branches:
    - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          # needed for accurate dates
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache build data
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install MKDocs
        run: pip install mkdocs-material
      - name: Build and deploy
        run: mkdocs gh-deploy --force
